sudo: false
cache:
  directories:
    - "$HOME/.m2"
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
script:
  - mvn -B -T2 -fae -Djava.awt.headless=true -Dall clean install
notifications:
  email: false
  on_failure: never
branches:
  only:
    - master
env: GDAL_LIBRARY_NAME=disabled_see_geot-4733
